[package]
name = "pepper"
version = "0.1.0"
authors = ["Matheus Lessa <matheus@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ropey = "1.1.0"
syntect = { version = "4.1", default-features = false, features = ["default-fancy"]}
crossterm = "0.17.1"
