name: Rust

on: [push, pull_request]

jobs:
  build:
    name: Test rust ${{ matrix.rust }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, 'windows-latest']
        rust: [stable]
        name: [pepper]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt
    - uses: actions/checkout@v1
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Upload unix binary
      uses: actions/upload-artifact@v1
      if: matrix.os != 'windows-latest'
      with:
        name: ${{ matrix.name }}-${{ matrix.os }}
        path: target/release/${{ matrix.name }}
    - name: Upload windows binary
      uses: actions/upload-artifact@v1
      if: matrix.os == 'windows-latest'
      with:
        name: ${{ matrix.name }}-${{ matrix.os }}
        path: target/release/${{ matrix.name }}.exe

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.name }}-ubuntu-latest
        path: dist/${{ matrix.name }}-ubuntu-latest
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.name }}-macOS-latest
        path: dist/${{ matrix.name }}-macOS-latest
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.name }}-windows-latest
        path: dist/${{ matrix.name }}-windows-latest
    - name: List release files
      run: find dist/
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload linux release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/${{ matrix.name }}-ubuntu-latest/${{ matrix.name }}
        asset_name: ${{ matrix.name }}-linux-x86_64
        asset_content_type: application/x-elf
    - name: Upload macos release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/${{ matrix.name }}-macOS-latest/${{ matrix.name }}
        asset_name: ${{ matrix.name }}-darwin-x86_64
        asset_content_type: application/x-mach-binary
    - name: Upload windows release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/${{ matrix.name }}-windows-latest/${{ matrix.name }}.exe
        asset_name: ${{ matrix.name }}-windows-x86_64.exe
        asset_content_type: application/vnd.microsoft.portable-executable