name: pepper

env:
  ubuntu_extension: ''
  macos_extension: ''
  windows_extension: '.exe'
  ubuntu_content_type: 'application/x-elf'
  macos_content_type: 'application/x-mach-binary'
  windows_content_type: 'application/vnd.microsoft.portable-executable'
  ubuntu_channel: linux
  macos_channel: mac
  windows_channel: windows
  default_suffix: ''
  demo_suffix: '-demo'

on: [push, pull_request]
jobs:
  build:
    name: rust ${{ matrix.rust }} on ${{ matrix.os }} ${{ matrix.features }} version
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        rust: [stable]
        features: [default, demo]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt
    - uses: actions/checkout@v1
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --verbose --release --features ${{ matrix.features }}
    - name: Upload ${ matrix.os }} binary
      uses: actions/upload-artifact@v1
      with:
        name: ${{ github.workflow }}-${{ env[format('{0}_channel', matrix.os)] }}${{ env[format('{0}_suffix', matrix.features)] }}
        path: target/release/${{ github.workflow }}${{ env[format('{0}_extension', matrix.os)] }}

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        features: [default, demo]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: ${{ github.workflow }}-${{ env[format('{0}_channel', matrix.os)] }}${{ env[format('{0}_suffix', matrix.features)] }}
        path: dist
    - name: List release files
      run: find dist/
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      if: matrix.features == 'demo'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        repo: pepper
    - name: Upload ${{ matrix.os }} ${{ matrix.features }} release asset
      uses: actions/upload-release-asset@v1.0.1
      if: matrix.features == 'demo'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/${{ github.workflow }}-${{ env[format('{0}_channel', matrix.os)] }}${{ env[format('{0}_suffix', matrix.features)] }}${{ env[format('{0}_extension', matrix.os)] }}
        asset_name: ${{ github.workflow }}-${{ env[format('{0}_channel', matrix.os)] }}${{ env[format('{0}_suffix', matrix.features)] }}${{ env[format('{0}_extension', matrix.os)] }}
        asset_content_type: ${{ env[format('{0}_content_type', matrix.os)] }}
    - name: Upload ${{ matrix.os }} ${{ matrix.features }} to itch
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_APIKEY }}
        CHANNEL: ${{ env[format('{0}_channel', matrix.os)] }}
        ITCH_GAME: ${{ github.workflow }}
        ITCH_USER: matheuslessarodrigues
        PACKAGE: dist/${{ github.workflow }}-${{ env[format('{0}_channel', matrix.os)] }}${{ env[format('{0}_suffix', matrix.features)] }}${{ env[format('{0}_extension', matrix.os)] }}
        VERSION: ${{ github.ref }}
